# Generated by Django 3.1.7 on 2021-08-18 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='joinat',
            field=models.DateField(default=datetime.datetime(2021, 8, 18, 6, 46, 24, 337977)),
        ),
    ]
